### ISSUE TITLE
Bug (?) with three level firearm implementation

### ISSUE THREAD

**Issue by pchristod** [ermaccer/Manhunt2.PluginMH2#3]
Hi,

I'm just wondering if this is a bug with the game, or the implementation of the Mod/Fix. It's my first time playing MH2, but with the three level firearm implementation and the interactive exec. I'm unable to trigger the first level with these two weapons, regardless of what motion I do with the Mouse. I'm talking about this:
![MH2](https://user-images.githubusercontent.com/17931739/166886635-fec2e047-8e21-4ef4-bef0-e360c1240f81.png)

I'm not even sure what that gesture is supposed to mean since right clicking immediately switched into aiming mode.

Thanks!

**Comment by ermaccer** [comment]
IIRC they don't have interactive data set up - some anims are missing in PC too. The PluginMH2 option is mostly code restoration, assets aren't taken care of.

**Comment by pchristod** [comment]
Thanks for the response! 
I see, so probably simply missing like you said. Too bad that MH2 has so much content cut/missing/incomplete. Either way thank you for the help & the Plugin, great help to make this Game even enjoyable with the various fixes.
